networks:
  modelci:
    name: modelci_gpu_network

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_USERNAME: modelci
      MONGO_INITDB_PASSWORD: modelci@2020
      MONGO_INITDB_DATABASE: modelci
    hostname: mongodb
    volumes:
      - ${PWD}/../scripts/init_db.js:/docker-entrypoint-initdb.d/init_db.js
    networks:
      - modelci

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    privileged: true
    restart: always
    ports:
      - 8080:8080
    environment:
      LD_LIBRARY_PATH: /usr/lib
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /usr/lib/libnvidia-ml.so.1:/usr/lib/libnvidia-ml.so.1
    networks:
      - modelci

  backend:
    image: mlmodelci/mlmodelci:cuda10.2-cudnn8
    container_name: modelci-backend
    hostname: modelci
    ports:
      - 8000:8000
    depends_on:
      - mongo
    networks:
      - modelci

  frontend:
    image: mlmodelci/frontend:latest
    container_name: modelci-frontend
    ports:
      - "3333:80"
    depends_on:
      - mongo
      - backend
    networks:
      - modelci